### PR TITLE
Add babel-plugin-transform-runtime

### LINKED ISSUE #7: Gatsby v2/regeneratorRuntime
Looks like there is an issue with expecting regeneratorRuntime/v2:

~~~
error Plugin gatsby-plugin-feed-generator returned an error


  ReferenceError: regeneratorRuntime is not defined
~~~

### PR DESCRIPTION
**Pull request by mlsgrnt**
Fixes build for gatsby v2 and closes #7

### CODE REVIEW

**Comment by markmichon** [comment]
Thanks for the PR @mlsgrnt 👍. Sorry about the holiday delay in getting to this.

**Comment by adamyonk** [comment]
I'm still seeing this error after 1.0.7:
```
error Plugin gatsby-plugin-feed-generator returned an error


  ReferenceError: regeneratorRuntime is not defined

  - gatsby-node.js:24
    [adamyonk.com]/[gatsby-plugin-feed-generator]/gatsby-node.js:24:47
```

Did the build not get updated or something?

**Comment by markmichon** [comment]
@adamyonk Give 1.0.8 a try. I suspect there was a caching issue on my end. I need to get CI set up on this repo sometime, especially now that gatsby is getting more popular.

**Comment by adamyonk** [comment]
@markmichon that fixed it, thanks for the rebuild!

**Pull request merged**
